package protocol

type Domain string

const (
	DomainProject   Domain = "project"
	DomainDocument  Domain = "document"
	DomainSchematic Domain = "schematic"
	DomainPcb       Domain = "pcb"
	DomainBoard     Domain = "board"
	DomainArtifact  Domain = "artifact"
	DomainSystem    Domain = "system"
	DomainDebug     Domain = "debug"
)

type ActionSpec struct {
	Name         string   `json:"name"`
	Domain       Domain   `json:"domain"`
	Phase        int      `json:"phase"`
	Mutates      bool     `json:"mutates"`
	NeedsWindow  bool     `json:"needsWindow"`
	NeedsConfirm bool     `json:"needsConfirm"`
	Description  string   `json:"description"`
	Inputs       []string `json:"inputs,omitempty"`
	Outputs      []string `json:"outputs,omitempty"`
	VerifyWith   []string `json:"verifyWith,omitempty"`
}

func AllActions() []ActionSpec {
	return []ActionSpec{
		{
			Name:        "system.health",
			Domain:      DomainSystem,
			Phase:       1,
			Description: "Check Go daemon and EasyEDA connector availability.",
			Outputs:     []string{"daemon status", "connected windows", "active window"},
		},
		{
			Name:        "project.current",
			Domain:      DomainProject,
			Phase:       1,
			NeedsWindow: true,
			Description: "Read current EasyEDA project information.",
			Outputs:     []string{"project uuid", "project name", "team/workspace context"},
		},
		{
			Name:        "document.current",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Read active editor document and schematic page context.",
			Outputs:     []string{"document uuid", "document type", "tab id"},
		},
		{
			Name:        "document.open",
			Domain:      DomainDocument,
			Phase:       1,
			Mutates:     false,
			NeedsWindow: true,
			Description: "Open any document (schematic page or PCB) by UUID and activate its editor tab. A generalization of schematic.page.open that works for all document types.",
			Inputs:      []string{"uuid"},
			Outputs:     []string{"tab id"},
		},
		// ── view (editor canvas, document-agnostic — schematic & PCB) ──────
		// All map to eda.dmt_EditorControl.* and act on the focused canvas.
		{
			Name:        "view.fit",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Zoom to fit all primitives in the focused canvas (适应全部, the `K` shortcut). Works on schematic and PCB. → eda.dmt_EditorControl.zoomToAllPrimitives.",
			Outputs:     []string{"region (left/right/top/bottom)"},
		},
		{
			Name:        "view.fit_selection",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Zoom to fit the currently selected primitives (适应选中). Select first (schematic.select / pcb), then fit. → eda.dmt_EditorControl.zoomToSelectedPrimitives.",
			Outputs:     []string{"region (left/right/top/bottom)"},
		},
		{
			Name:        "view.zoom",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Pan/zoom to a center coordinate and/or scale ratio. Omitted fields keep their current value; scale is a percent (200 = 200%). Sch/symbol units are 0.01inch, PCB/footprint units are mil. → eda.dmt_EditorControl.zoomTo.",
			Inputs:      []string{"x optional", "y optional", "scale optional"},
			Outputs:     []string{"region (left/right/top/bottom)"},
		},
		{
			Name:        "view.region",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Zoom to a rectangular region given by its two X and two Y bounds (canvas units: sch 0.01inch, PCB mil). → eda.dmt_EditorControl.zoomToRegion.",
			Inputs:      []string{"left", "right", "top", "bottom"},
			Outputs:     []string{"ok"},
		},
		{
			Name:        "schematic.pages.list",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "List schematic documents and schematic pages in the current project.",
			Outputs:     []string{"schematic uuid list", "schematic page uuid list"},
		},
		{
			Name:        "schematic.page.open",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     false,
			NeedsWindow: true,
			Description: "Open or activate a schematic page by uuid.",
			Inputs:      []string{"schematicPageUuid"},
			Outputs:     []string{"tab id", "current document"},
		},
		// ── sheet / page management + 明细表 (title block) ─────────────────
		// All map to eda.dmt_Schematic.*. NOTE: EasyEDA Pro exposes no
		// set-paper-size (A4/A3) API; the title block is the editable "图纸" surface.
		{
			Name:        "schematic.titleblock.get",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Read a schematic page's 明细表 (title block): show flag + per-field data. Defaults to the focused page; pass pageUuid for another. Read this first to discover the editable field keys before titleblock.modify.",
			Inputs:      []string{"pageUuid optional"},
			Outputs:     []string{"showTitleBlock", "titleBlockData (field keys + values)"},
		},
		{
			Name:        "schematic.titleblock.modify",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Modify the focused page's 明细表 (title block): toggle visibility and/or patch fields. titleBlockData carries only items to change ({key:{showTitle?,showValue?,value?}}); unknown keys ignored, untouched items keep current value.",
			Inputs:      []string{"showTitleBlock optional", "titleBlockData optional"},
			Outputs:     []string{"ok"},
			VerifyWith:  []string{"schematic.titleblock.get"},
		},
		{
			Name:        "schematic.page.create",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a new schematic page under a schematic document.",
			Inputs:      []string{"schematicUuid"},
			Outputs:     []string{"pageUuid"},
			VerifyWith:  []string{"schematic.pages.list"},
		},
		{
			Name:        "schematic.page.rename",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Rename a schematic page.",
			Inputs:      []string{"pageUuid", "name"},
			Outputs:     []string{"ok"},
		},
		{
			Name:         "schematic.page.delete",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete a schematic page (no undo).",
			Inputs:       []string{"pageUuid"},
			Outputs:      []string{"ok"},
		},
		{
			Name:         "schematic.page.clear",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Clear the ACTIVE schematic page: delete every page-level primitive — components, net flags/ports/labels (all are components), wires, buses, and graphics (arcs/circles/rectangles/polygons/text) — optionally preserving the sheet/title block (图框). schematic.component.delete only removes components and silently leaves wires/buses/graphics behind, so the page looks clean in components.list while residual primitives remain; use this for a true page reset (generate → detect → clear → retry). No undo — dryRun reports counts without deleting.",
			Inputs:       []string{"preserveSheet optional (default true)", "dryRun optional (default false)"},
			Outputs:      []string{"deleted (counts by primitive type)", "total", "deletedIds", "preserveSheet", "dryRun"},
			VerifyWith:   []string{"schematic.components.list", "schematic.snapshot"},
		},
		{
			Name:        "schematic.rename",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Rename a schematic document (the whole sheet, not a single page). May also rename a linked reuse-module symbol + PCB.",
			Inputs:      []string{"schematicUuid", "name"},
			Outputs:     []string{"ok"},
		},
		{
			Name:        "schematic.components.list",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "List components on the active schematic page. includeBBox attaches each component's rendered extent {minX,minY,maxX,maxY} (used by `easyeda sch layout-lint` for overlap/spacing checks). NOTE: the component/symbol/footprint/uniqueId fields are placed-INSTANCE ids — they are NOT device-library uuids and cannot be replayed into `schematic.component.place`. To re-place the same part, get a fresh device uuid from `schematic.library.search`.",
			Inputs:      []string{"allPages optional", "includePins optional", "includeBBox optional"},
			Outputs:     []string{"component primitives", "designator", "name", "pins", "bbox"},
		},
		{
			Name:        "schematic.component.place",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Place a device/component from library identity at coordinates. `uuid` must be a device-library uuid (from schematic.library.search), NOT a placed-instance id from schematic.components.list — an instance uuid hangs the EasyEDA API.",
			Inputs:      []string{"libraryUuid", "uuid (device-library uuid, not an instance id)", "x", "y", "rotation optional", "mirror optional"},
			Outputs:     []string{"primitive id", "component state"},
			VerifyWith:  []string{"schematic.component.get", "schematic.snapshot"},
		},
		{
			Name:        "schematic.component.modify",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Modify component position, designator, name, BOM flags, or custom properties.",
			Inputs:      []string{"primitiveId", "patch"},
			Outputs:     []string{"component state"},
			VerifyWith:  []string{"schematic.component.get"},
		},
		{
			Name:         "schematic.component.delete",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete schematic component primitives.",
			Inputs:       []string{"primitiveIds"},
			Outputs:      []string{"deleted"},
			VerifyWith:   []string{"schematic.components.list"},
		},
		{
			Name:         "schematic.primitives.delete",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete schematic primitives of ANY type by id (components, net flags/ports/labels, wires, buses, graphics) — generalizes schematic.component.delete beyond components by routing each id to its owning sch_Primitive* class. Omit primitiveIds to delete the current selection (select first via schematic.select), enabling a 'select-all then delete' flow. No undo.",
			Inputs:       []string{"primitiveIds optional (string or string[]; default = current selection)"},
			Outputs:      []string{"deleted (counts by primitive type)", "total", "notFound", "deletedIds"},
			VerifyWith:   []string{"schematic.components.list", "schematic.snapshot"},
		},
		{
			Name:        "schematic.wire.create",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a schematic wire polyline.",
			Inputs:      []string{"points", "net optional", "style optional"},
			Outputs:     []string{"primitive id", "wire state"},
			VerifyWith:  []string{"schematic.primitive.get", "schematic.snapshot"},
		},
		{
			Name:        "schematic.netflag.create",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create power, ground, analog ground, protective ground, net port, or short-circuit flag.",
			Inputs:      []string{"kind", "net", "x", "y", "rotation optional"},
			Outputs:     []string{"primitive id", "component state"},
			VerifyWith:  []string{"schematic.snapshot"},
		},
		{
			Name:        "schematic.pin.set_no_connect",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Mark (or clear) a component pin's no-connect flag (非连接标识, the X marker) — tells DRC the pin is intentionally unconnected so it stops reporting 'un-connected pin'. Targets pins by designator + pin number; pass noConnected=false to clear. ⚠️ KNOWN PLATFORM LIMITATION: on EasyEDA Pro 3.2.x, pin.setState_NoConnected is a NO-OP (the pin primitive has no noConnected field — verified by re-pull, DRC re-run, and snapshot: no NC mark is placed, DRC still reports the pin as floating). The action now VERIFIES the write and FAILS with a clear error when it doesn't take, instead of silently 'succeeding'. There is no public eda.* API to place a 非连接标识 on this build; use schematic.check to enumerate floating pins.",
			Inputs:      []string{"designator", "pins", "noConnected optional"},
			Outputs:     []string{"designator", "primitive id", "pins[].noConnected", "notApplied[]"},
			VerifyWith:  []string{"schematic.components.list", "schematic.drc.check"},
		},
		{
			Name:        "schematic.library.search",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Search the EasyEDA device library by free-text query (MPN, value+package, or a name like 'ESP32-S3-WROOM-1'). Returns a relevance-ranked list (with score) of libraryUuid + uuid ready for schematic.component.place.",
			Inputs:      []string{"query", "limit optional"},
			Outputs:     []string{"components[].libraryUuid", "components[].uuid", "components[].name", "components[].value", "components[].footprintName", "components[].lcsc", "components[].description"},
		},
		{
			Name:        "schematic.library.get_by_lcsc",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Resolve one or more LCSC C-numbers (e.g. C6186) directly to device-library identity — libraryUuid + uuid ready for schematic.component.place — skipping free-text ranking. Use when you already know the exact part (from standard-parts.json or a BOM). Reports a notFound list for any C-number the library did not resolve.",
			Inputs:      []string{"lcscIds (string or string[] of C-numbers)"},
			Outputs:     []string{"components[].lcsc", "components[].libraryUuid", "components[].uuid", "components[].name", "components[].value", "components[].footprintName", "components[].description", "notFound"},
		},
		{
			Name:        "schematic.power.connect_pin",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Composite: stub a wire out of a pin and place a netflag/netport at its far end in one call — structurally prevents the 'netflag overlaps pin' DRC fatal. Direction/offset/rotation default from kind and can be overridden; flag orientation follows schematic-layout-conventions.md §3.5.",
			Inputs:      []string{"pinX", "pinY", "kind", "net", "direction optional", "offset optional", "rotation optional"},
			Outputs:     []string{"wire primitiveId", "flag primitiveId", "end point", "rotation"},
			VerifyWith:  []string{"schematic.snapshot", "schematic.drc.check"},
		},
		{
			Name:        "schematic.select",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Select schematic primitives by id and return the active selection.",
			Inputs:      []string{"primitiveIds"},
			Outputs:     []string{"selected primitive ids"},
		},
		{
			Name:        "schematic.snapshot",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Capture current rendered area image as an artifact. Zooms to fit all primitives (适应全部) BY DEFAULT before capturing so the whole sheet lands in frame (and the viewport change nudges a redraw); pass fit=false to keep the current viewport. WARNING: EasyEDA may not auto-redraw after API edits, so the image can be a STALE frame — judge state by data (sch list/getAll), not the screenshot. Returns primitiveCount + capturedAt; if primitiveCount changed between two snapshots but the image is unchanged, the frame is stale.",
			Inputs:      []string{"fit optional (default true)"},
			Outputs:     []string{"artifact id", "file path", "mime type", "primitiveCount", "fitted", "capturedAt"},
		},
		{
			Name:        "schematic.drc.check",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Run schematic DRC and normalize the result into per-violation detail. Each violation carries {level, rule, message, primitiveIds, designators, x, y} (best-effort projection over the SDK shape, raw kept) plus a severity `summary` and a `fatal` count (error+fatal severities) for the design-flow S5 gate. `includeVerboseError` (default true) selects the detailed/array SDK overload. NOTE: the EDA schematic DRC API only returns an aggregate {count,type} (no per-item detail) — for the itemized findings the UI panel shows (which pins float, etc.), use schematic.check.",
			Inputs:      []string{"strict", "includeVerboseError"},
			Outputs:     []string{"passed", "fatal", "summary", "violations"},
		},
		{
			Name:        "schematic.check",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Reconstructed per-item design check that the SDK's schematic DRC API cannot expose (eda.sch_Drc.check returns only an aggregate {count,type}) and that complements layout-lint (which only sees component bbox overlap). Computes findings geometrically from primitives. Rules: (1) floating pins — a pin is connected iff a wire touches its coordinate, NC-marked excluded, grouped by component as {designator, pins[]} (the exact input schematic.pin.set_no_connect takes); (2) wire-crossing — two wire segments cross in their interiors (routing tangle; shared endpoints/junctions excluded), reported with the intersection point; (3) wire-over-pin — a pin sits in a wire's interior (EasyEDA trims+connects there → unintended short). Returns {passed, summary{floatingPins,wireCrossings,wireOverPins,…}, findings[]}.",
			Inputs:      []string{"allPages optional"},
			Outputs:     []string{"passed", "summary", "findings"},
		},
		{
			Name:        "schematic.save",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Save active schematic document.",
			Outputs:     []string{"saved"},
		},
		{
			Name:        "schematic.export.netlist",
			Domain:      DomainArtifact,
			Phase:       1,
			NeedsWindow: true,
			Description: "Export schematic netlist as an artifact.",
			Inputs:      []string{"netlistType optional"},
			Outputs:     []string{"artifact id", "file path", "netlist type"},
		},
		{
			Name:        "schematic.export.bom",
			Domain:      DomainArtifact,
			Phase:       1,
			NeedsWindow: true,
			Description: "Export schematic BOM as csv or xlsx artifact.",
			Inputs:      []string{"fileType", "template optional", "columns optional"},
			Outputs:     []string{"artifact id", "file path", "file type"},
		},
		// ─── PCB (Phase 2 — read-only skeleton) ──────────────────────────
		// Connectivity probe + inspection surface for the upcoming PCB
		// layout/routing feature. All read-only; mirrors the schematic read
		// actions against the eda.pcb_* namespaces. See docs/phase-2-pcb.md.
		{
			Name:        "pcb.documents.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all PCB documents in the current project. Returns uuid + name for each board; pass uuid to document.open to switch to that PCB.",
			Outputs:     []string{"pcbs[].uuid", "pcbs[].name", "pcbs[].parentProjectUuid", "count"},
		},
		{
			Name:        "pcb.components.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List placed footprints/components on the active PCB, with layer, coordinates, rotation, lock, optional bbox (rendered extent, for overlap/spacing reasoning), and optional pads.",
			Inputs:      []string{"layer optional", "includeBBox optional", "includePads optional"},
			Outputs:     []string{"components[].primitiveId", "components[].designator", "components[].layer", "components[].x", "components[].y", "components[].rotation", "components[].bbox", "components[].pads", "count"},
		},
		{
			Name:        "pcb.layers.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all layers of the active PCB (id, name, type, color, visibility, lock), plus the current layer and copper-layer count.",
			Outputs:     []string{"layers", "currentLayer", "copperLayerCount", "count"},
		},
		{
			Name:        "pcb.nets.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all nets on the active PCB with name, length, and color.",
			Outputs:     []string{"nets[].net", "nets[].length", "nets[].color", "count"},
		},
		{
			Name:        "pcb.report",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read-only PCB design report driven by per-net copper length: every net's routed length, each net class's aggregate length, differential-pair P/N lengths + skew (|lenP-lenN|), and equal-length-group per-net lengths + spread (max-min). Pure read — no DRC run. pcb_Drc.* reads may require the PCB to be the active/foreground tab.",
			Outputs:     []string{"nets[].net", "nets[].length", "netClasses[].name", "netClasses[].totalLength", "differentialPairs[].skew", "equalLengthNetGroups[].spread"},
		},
		// ─── PCB (Phase 2 — schematic→PCB sync + component layout) ────────
		// Components arrive on the board via pcb.import_changes (from the
		// schematic), then get laid out with pcb.component.modify. See
		// docs/phase-2-pcb.md.
		{
			Name:        "pcb.board.info",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the current Board (schematic+PCB linkage) and current PCB info — the prerequisite context for pcb.import_changes.",
			Outputs:     []string{"linked", "board", "pcb"},
		},
		// ── board (板子/组合 — the schematic↔PCB binding) ──────────────────
		// A Board groups exactly one schematic + one PCB; it is identified by
		// NAME (not uuid). All map to eda.dmt_Board.*. Domain-agnostic routing.
		{
			Name:        "board.list",
			Domain:      DomainBoard,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all Boards (板子) in the current project. A Board binds one schematic + one PCB into a group — this is how schematic and PCB are kept together (and what import_changes follows).",
			Outputs:     []string{"boards (name + schematic + pcb)"},
		},
		{
			Name:        "board.current",
			Domain:      DomainBoard,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the current Board (its bound schematic + PCB).",
			Outputs:     []string{"linked", "board"},
		},
		{
			Name:        "board.create",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a Board binding a schematic and/or a PCB into one group (组合). Pass schematicUuid and/or pcbUuid; returns the new board name.",
			Inputs:      []string{"schematicUuid optional", "pcbUuid optional"},
			Outputs:     []string{"boardName"},
			VerifyWith:  []string{"board.list"},
		},
		{
			Name:        "board.rename",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Rename a Board (板子) by its current name.",
			Inputs:      []string{"name", "newName"},
			Outputs:     []string{"ok"},
		},
		{
			Name:        "board.copy",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Copy a Board (its schematic + PCB) into a new Board; returns the new board name.",
			Inputs:      []string{"name"},
			Outputs:     []string{"boardName"},
			VerifyWith:  []string{"board.list"},
		},
		{
			Name:         "board.delete",
			Domain:       DomainBoard,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete a Board by name (无 undo). Removes the schematic↔PCB grouping and its documents.",
			Inputs:       []string{"name"},
			Outputs:      []string{"ok"},
		},
		{
			Name:         "pcb.import_changes",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Sync the schematic netlist/components into the active PCB (从原理图导入变更) — the primary way components arrive on the board. Ensures a Board links the schematic and PCB first, then recomputes ratlines.",
			Inputs:       []string{"schematicUuid optional", "ensureBoard optional (default true)", "recomputeRatline optional (default true)"},
			Outputs:      []string{"imported", "createdBoard", "board", "reason"},
			VerifyWith:   []string{"pcb.components.list", "pcb.nets.list"},
		},
		{
			Name:        "pcb.component.modify",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Lay out a component on the active PCB: move (x/y), rotate, flip layer (top/bottom), lock, or set designator/BOM flags. Pull a fresh primitiveId first (no programmatic undo).",
			Inputs:      []string{"primitiveId", "patch"},
			Outputs:     []string{"component state"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:         "pcb.component.delete",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete PCB component primitives. No programmatic undo — snapshot before/after via the audit log.",
			Inputs:       []string{"primitiveIds"},
			Outputs:      []string{"deleted"},
			VerifyWith:   []string{"pcb.components.list"},
		},
		// ─── PCB layout-adjustment (deterministic; no native align/grid API) ──
		// Read each component's bbox + anchor, compute, write absolute x/y.
		// Operate on the current selection by default, or explicit primitiveIds.
		{
			Name:        "pcb.align",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Align components by an edge or center. mode = left|right|top|bottom|centerX|centerY (top/bottom are y-up: top = larger y). Aligns to the group extent. Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"mode", "primitiveIds optional"},
			Outputs:     []string{"moved[].primitiveId", "moved[].designator", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.distribute",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Evenly space component centers along an axis. axis = x|y. Keeps the two extreme components fixed and distributes the rest between them. Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"axis", "primitiveIds optional"},
			Outputs:     []string{"moved[].primitiveId", "moved[].designator", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.grid_snap",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Snap component anchors to a grid: round x/y to the nearest multiple of grid (in PCB data units, mil-scale). Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"grid", "primitiveIds optional"},
			Outputs:     []string{"snapped[].primitiveId", "snapped[].from", "snapped[].to", "grid", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.components.move",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Translate components by a relative (dx, dy) offset — nudge a group without recomputing absolute coordinates. Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"dx", "dy", "primitiveIds optional"},
			Outputs:     []string{"moved[].primitiveId", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.components.arrange",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Coarse auto-layout SEED: cluster by shared local nets (mode=cluster) or pack a flat grid (mode=grid), grid-packing each cluster into a tidy block with gutters; skips locked components. Mechanical first pass only — apply the placement priorities in pcb-layout-conventions.md afterward.",
			Inputs:      []string{"mode optional (cluster|grid, default cluster)", "primitiveIds optional", "pitch optional", "gutter optional", "cols optional"},
			Outputs:     []string{"mode", "groups", "moved[].primitiveId", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.drc.check",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Run PCB DRC, normalized to {passed, violations}; violations are grouped by error type then net. Requires the PCB to be the active/foreground document.",
			Inputs:      []string{"strict optional"},
			Outputs:     []string{"passed", "violations"},
		},
		{
			Name:        "pcb.drc.rules",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the active PCB's DRC rule configuration (clearances, track widths, via sizes, …) WITHOUT running a check — inspect what pcb.drc.check enforces, or feed real rule values into layout-lint / design-flow gates. Requires the PCB to be the active/foreground document.",
			Outputs:     []string{"rules"},
		},
		// ─── PCB routing (copper tracks + vias) ──────────────────────────
		// Real routing primitives — additive creates (no confirm), like the
		// schematic wire/netflag creates. Bind to a net by NAME; pull layer ids
		// from pcb.layers.list and net names from pcb.nets.list first.
		{
			Name:        "pcb.line.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a copper track (导线) on the active PCB: a line segment on a copper layer (TOP=1, BOTTOM=2; inner-copper ids are higher — read them from pcb.layers.list, id 3 is silkscreen not copper) with a width, optionally bound to a net. Coordinates are mil, y-up. create() is lenient — the action verifies a primitive came back. No PCB autosave yet; save explicitly.",
			Inputs:      []string{"startX", "startY", "endX", "endY", "layer optional (default 1=TOP)", "lineWidth optional (default 6)", "net optional"},
			Outputs:     []string{"primitiveId", "net", "layer", "start", "end", "lineWidth"},
			VerifyWith:  []string{"pcb.drc.check"},
		},
		{
			Name:        "pcb.via.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Place a via (过孔) at (x,y) on the active PCB with a hole + outer diameter (mil), optionally bound to a net. Coordinates are mil, y-up. create() is lenient — the action verifies a primitive came back. No PCB autosave yet; save explicitly.",
			Inputs:      []string{"x", "y", "holeDiameter optional", "diameter optional", "net optional"},
			Outputs:     []string{"primitiveId", "net", "x", "y", "holeDiameter", "diameter"},
			VerifyWith:  []string{"pcb.drc.check"},
		},
		// ─── Board outline (板框) — closed polyline on the BOARD_OUTLINE layer ──
		// Curves are line-segment approximated (native arcs do not commit on the
		// current build). Shape-generation recipes (rect/rounded-rect/circle/
		// instrument) live in the easyeda-pcb skill; these actions just render points.
		{
			Name:         "pcb.outline.set",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Set the board outline from a closed polygon of points (mil, y-up). Replaces any existing outline. The agent generates the points for the desired shape (rectangle/rounded-rect/circle/instrument); curves are approximated by line segments. Reports whether all components fall inside.",
			Inputs:       []string{"points ([[x,y],...] mil)", "replace optional (default true)", "lineWidth optional"},
			Outputs:      []string{"segments", "zoomed", "bbox", "allInside", "outside"},
			VerifyWith:   []string{"pcb.outline.get"},
		},
		{
			Name:        "pcb.outline.get",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the current board outline (segment/arc counts + bounding box).",
			Outputs:     []string{"segments", "arcs", "bbox"},
		},
		{
			Name:         "pcb.outline.clear",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Remove the current board outline (all primitives on the BOARD_OUTLINE layer).",
			Outputs:      []string{"removed"},
			VerifyWith:   []string{"pcb.outline.get"},
		},
		{
			Name:         "debug.exec_js",
			Domain:       DomainDebug,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Run raw eda.* JavaScript in the connector. Escape hatch for operations without a typed action; confirmation-gated, not for normal workflows.",
			Inputs:       []string{"code"},
			Outputs:      []string{"value"},
		},
	}
}
