package protocol

type Domain string

const (
	DomainProject   Domain = "project"
	DomainDocument  Domain = "document"
	DomainSchematic Domain = "schematic"
	DomainPcb       Domain = "pcb"
	DomainBoard     Domain = "board"
	DomainArtifact  Domain = "artifact"
	DomainSystem    Domain = "system"
	DomainDebug     Domain = "debug"
)

type ActionSpec struct {
	Name         string   `json:"name"`
	Domain       Domain   `json:"domain"`
	Phase        int      `json:"phase"`
	Mutates      bool     `json:"mutates"`
	NeedsWindow  bool     `json:"needsWindow"`
	NeedsConfirm bool     `json:"needsConfirm"`
	Description  string   `json:"description"`
	Inputs       []string `json:"inputs,omitempty"`
	Outputs      []string `json:"outputs,omitempty"`
	VerifyWith   []string `json:"verifyWith,omitempty"`
}

func AllActions() []ActionSpec {
	return []ActionSpec{
		{
			Name:        "system.health",
			Domain:      DomainSystem,
			Phase:       1,
			Description: "Check Go daemon and EasyEDA connector availability.",
			Outputs:     []string{"daemon status", "connected windows", "active window"},
		},
		{
			Name:        "system.notify",
			Domain:      DomainSystem,
			Phase:       1,
			NeedsWindow: true,
			Description: "Show a non-blocking toast INSIDE the EasyEDA window — the design flow announces each stage as it passes (完成 X,下一步 Y) so the user can watch progress live.",
			Inputs:      []string{"message (required)", "type optional (info|success|warn|error|question, default info)", "duration optional (seconds, default 3)"},
			Outputs:     []string{"shown", "message", "type"},
		},
		{
			Name:        "project.current",
			Domain:      DomainProject,
			Phase:       1,
			NeedsWindow: true,
			Description: "Read current EasyEDA project information.",
			Outputs:     []string{"project uuid", "project name", "team/workspace context"},
		},
		{
			Name:        "document.current",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Read active editor document and schematic page context.",
			Outputs:     []string{"document uuid", "document type", "tab id"},
		},
		{
			Name:        "document.open",
			Domain:      DomainDocument,
			Phase:       1,
			Mutates:     false,
			NeedsWindow: true,
			Description: "Open any document (schematic page or PCB) by UUID and activate its editor tab. A generalization of schematic.page.open that works for all document types.",
			Inputs:      []string{"uuid"},
			Outputs:     []string{"tab id"},
		},
		// ── view (editor canvas, document-agnostic — schematic & PCB) ──────
		// All map to eda.dmt_EditorControl.* and act on the focused canvas.
		{
			Name:        "view.fit",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Zoom to fit all primitives in the focused canvas (适应全部, the `K` shortcut). Works on schematic and PCB. → eda.dmt_EditorControl.zoomToAllPrimitives.",
			Outputs:     []string{"region (left/right/top/bottom)"},
		},
		{
			Name:        "view.fit_selection",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Zoom to fit the currently selected primitives (适应选中). Select first (schematic.select / pcb), then fit. → eda.dmt_EditorControl.zoomToSelectedPrimitives.",
			Outputs:     []string{"region (left/right/top/bottom)"},
		},
		{
			Name:        "view.zoom",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Pan/zoom to a center coordinate and/or scale ratio. Omitted fields keep their current value; scale is a percent (200 = 200%). Sch/symbol units are 0.01inch, PCB/footprint units are mil. → eda.dmt_EditorControl.zoomTo.",
			Inputs:      []string{"x optional", "y optional", "scale optional"},
			Outputs:     []string{"region (left/right/top/bottom)"},
		},
		{
			Name:        "view.region",
			Domain:      DomainDocument,
			Phase:       1,
			NeedsWindow: true,
			Description: "Zoom to a rectangular region given by its two X and two Y bounds (canvas units: sch 0.01inch, PCB mil). → eda.dmt_EditorControl.zoomToRegion.",
			Inputs:      []string{"left", "right", "top", "bottom"},
			Outputs:     []string{"ok"},
		},
		{
			Name:        "schematic.pages.list",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "List schematic documents and schematic pages in the current project.",
			Outputs:     []string{"schematic uuid list", "schematic page uuid list"},
		},
		{
			Name:        "schematic.page.open",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     false,
			NeedsWindow: true,
			Description: "Open or activate a schematic page by uuid.",
			Inputs:      []string{"schematicPageUuid"},
			Outputs:     []string{"tab id", "current document"},
		},
		// ── sheet / page management + 明细表 (title block) ─────────────────
		// All map to eda.dmt_Schematic.*. NOTE: EasyEDA Pro exposes no
		// set-paper-size (A4/A3) API; the title block is the editable "图纸" surface.
		{
			Name:        "schematic.titleblock.get",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Read a schematic page's 明细表 (title block): show flag + per-field data. Defaults to the focused page; pass pageUuid for another. Read this first to discover the editable field keys before titleblock.modify.",
			Inputs:      []string{"pageUuid optional"},
			Outputs:     []string{"showTitleBlock", "titleBlockData (field keys + values)"},
		},
		{
			Name:        "schematic.titleblock.modify",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Modify the focused page's 明细表 (title block): toggle visibility and/or patch fields. titleBlockData carries only items to change ({key:{showTitle?,showValue?,value?}}); unknown keys ignored, untouched items keep current value.",
			Inputs:      []string{"showTitleBlock optional", "titleBlockData optional"},
			Outputs:     []string{"ok"},
			VerifyWith:  []string{"schematic.titleblock.get"},
		},
		{
			Name:        "schematic.page.create",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a new schematic page under a schematic document.",
			Inputs:      []string{"schematicUuid"},
			Outputs:     []string{"pageUuid"},
			VerifyWith:  []string{"schematic.pages.list"},
		},
		{
			Name:        "schematic.page.rename",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Rename a schematic page.",
			Inputs:      []string{"pageUuid", "name"},
			Outputs:     []string{"ok"},
		},
		{
			Name:         "schematic.page.delete",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete a schematic page (no undo).",
			Inputs:       []string{"pageUuid"},
			Outputs:      []string{"ok"},
		},
		{
			Name:         "schematic.page.clear",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Clear the ACTIVE schematic page: delete every page-level primitive — components, net flags/ports/labels (all are components), wires, buses, and graphics (arcs/circles/rectangles/polygons/text) — optionally preserving the sheet/title block (图框). schematic.component.delete only removes components and silently leaves wires/buses/graphics behind, so the page looks clean in components.list while residual primitives remain; use this for a true page reset (generate → detect → clear → retry). No undo — dryRun reports counts without deleting.",
			Inputs:       []string{"preserveSheet optional (default true)", "dryRun optional (default false)"},
			Outputs:      []string{"deleted (counts by primitive type)", "total", "deletedIds", "preserveSheet", "dryRun"},
			VerifyWith:   []string{"schematic.components.list", "schematic.snapshot"},
		},
		{
			Name:        "schematic.rename",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Rename a schematic document (the whole sheet, not a single page). May also rename a linked reuse-module symbol + PCB.",
			Inputs:      []string{"schematicUuid", "name"},
			Outputs:     []string{"ok"},
		},
		{
			Name:        "schematic.components.list",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "List components on the active schematic page. includeBBox attaches each component's rendered extent {minX,minY,maxX,maxY} (used by `easyeda sch layout-lint` for overlap/spacing checks). NOTE: the component/symbol/footprint/uniqueId fields are placed-INSTANCE ids — they are NOT device-library uuids and cannot be replayed into `schematic.component.place`. To re-place the same part, get a fresh device uuid from `schematic.library.search`.",
			Inputs:      []string{"allPages optional", "includePins optional", "includeBBox optional"},
			Outputs:     []string{"component primitives", "designator", "name", "pins", "bbox"},
		},
		{
			Name:        "schematic.component.place",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Place a device/component from library identity at coordinates. `uuid` must be a device-library uuid (from schematic.library.search), NOT a placed-instance id from schematic.components.list — an instance uuid hangs the EasyEDA API.",
			Inputs:      []string{"libraryUuid", "uuid (device-library uuid, not an instance id)", "x", "y", "rotation optional", "mirror optional"},
			Outputs:     []string{"primitive id", "component state"},
			VerifyWith:  []string{"schematic.component.get", "schematic.snapshot"},
		},
		{
			Name:        "schematic.component.modify",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Modify component position, designator, name, BOM flags, or custom properties.",
			Inputs:      []string{"primitiveId", "patch"},
			Outputs:     []string{"component state"},
			VerifyWith:  []string{"schematic.component.get"},
		},
		{
			Name:         "schematic.component.delete",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete schematic component primitives.",
			Inputs:       []string{"primitiveIds"},
			Outputs:      []string{"deleted"},
			VerifyWith:   []string{"schematic.components.list"},
		},
		{
			Name:         "schematic.primitives.delete",
			Domain:       DomainSchematic,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete schematic primitives of ANY type by id (components, net flags/ports/labels, wires, buses, graphics) — generalizes schematic.component.delete beyond components by routing each id to its owning sch_Primitive* class. Omit primitiveIds to delete the current selection (select first via schematic.select), enabling a 'select-all then delete' flow. No undo.",
			Inputs:       []string{"primitiveIds optional (string or string[]; default = current selection)"},
			Outputs:      []string{"deleted (counts by primitive type)", "total", "notFound", "deletedIds"},
			VerifyWith:   []string{"schematic.components.list", "schematic.snapshot"},
		},
		{
			Name:        "schematic.wire.create",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a schematic wire polyline.",
			Inputs:      []string{"points", "net optional", "style optional"},
			Outputs:     []string{"primitive id", "wire state"},
			VerifyWith:  []string{"schematic.primitive.get", "schematic.snapshot"},
		},
		{
			Name:        "schematic.netflag.create",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create power, ground, analog ground, protective ground, net port, or short-circuit flag.",
			Inputs:      []string{"kind", "net", "x", "y", "rotation optional"},
			Outputs:     []string{"primitive id", "component state"},
			VerifyWith:  []string{"schematic.snapshot"},
		},
		{
			Name:        "schematic.pin.set_no_connect",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Mark (or clear) a component pin's no-connect flag (非连接标识, the X marker) — tells DRC the pin is intentionally unconnected so it stops reporting 'un-connected pin'. Targets pins by designator + pin number; pass noConnected=false to clear. ⚠️ KNOWN PLATFORM LIMITATION: on EasyEDA Pro 3.2.x, pin.setState_NoConnected is a NO-OP (the pin primitive has no noConnected field — verified by re-pull, DRC re-run, and snapshot: no NC mark is placed, DRC still reports the pin as floating). The action now VERIFIES the write and FAILS with a clear error when it doesn't take, instead of silently 'succeeding'. There is no public eda.* API to place a 非连接标识 on this build; use schematic.check to enumerate floating pins.",
			Inputs:      []string{"designator", "pins", "noConnected optional"},
			Outputs:     []string{"designator", "primitive id", "pins[].noConnected", "notApplied[]"},
			VerifyWith:  []string{"schematic.components.list", "schematic.drc.check"},
		},
		{
			Name:        "schematic.library.search",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Search the EasyEDA device library by free-text query (MPN, value+package, or a name like 'ESP32-S3-WROOM-1'). Returns a relevance-ranked list (with score) of libraryUuid + uuid ready for schematic.component.place.",
			Inputs:      []string{"query", "limit optional"},
			Outputs:     []string{"components[].libraryUuid", "components[].uuid", "components[].name", "components[].value", "components[].footprintName", "components[].lcsc", "components[].description"},
		},
		{
			Name:        "schematic.library.get_by_lcsc",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Resolve one or more LCSC C-numbers (e.g. C6186) directly to device-library identity — libraryUuid + uuid ready for schematic.component.place — skipping free-text ranking. Use when you already know the exact part (from standard-parts.json or a BOM). Reports a notFound list for any C-number the library did not resolve.",
			Inputs:      []string{"lcscIds (string or string[] of C-numbers)"},
			Outputs:     []string{"components[].lcsc", "components[].libraryUuid", "components[].uuid", "components[].name", "components[].value", "components[].footprintName", "components[].description", "notFound"},
		},
		{
			Name:        "schematic.rebind.footprint",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Swap a placed component's footprint via the five-step binding (lib_Device.modify → delete → create → restore) — modify alone cannot change a placed instance's footprint reference. Matches by footprint name (exact; same-name-multi or miss errors out — pass footprintUuid to bind directly). Reverse-resolves an empty device libraryUuid from the project library first. Captures and restores designator/position/rotation/mirror/BOM flags/manufacturer/supplier/otherProperty; rolls back on failure. Re-placing mints a NEW primitiveId — wires may need re-drawing, so verify with sch drc/check.",
			Inputs:      []string{"primitiveId", "footprint (name) OR footprintUuid (+footprintLibraryUuid)", "scope optional (default project)"},
			Outputs:     []string{"primitiveId (new)", "previousPrimitiveId", "footprint", "device", "component state"},
			VerifyWith:  []string{"schematic.components.list", "schematic.drc.check"},
		},
		{
			Name:        "schematic.rebind.symbol",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Swap a placed component's symbol via the same five-step binding as schematic.rebind.footprint. Matches by symbol name (exact; pass symbolUuid to disambiguate). Captures and restores original state and rolls back on failure. Re-placing mints a NEW primitiveId — verify connectivity with sch drc/check.",
			Inputs:      []string{"primitiveId", "symbol (name) OR symbolUuid (+symbolLibraryUuid)", "scope optional (default project)"},
			Outputs:     []string{"primitiveId (new)", "previousPrimitiveId", "symbol", "device", "component state"},
			VerifyWith:  []string{"schematic.components.list", "schematic.drc.check"},
		},
		{
			Name:        "schematic.power.connect_pin",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Composite: stub a wire out of a pin and place a netflag/netport at its far end in one call — structurally prevents the 'netflag overlaps pin' DRC fatal. `direction` is the VISUAL outward direction on the canvas (up=higher, down=lower; coords are y-DOWN so 'up' moves the endpoint to a smaller y). Direction/offset/rotation default from kind and can be overridden; flag orientation follows schematic-layout-conventions.md §3.5.",
			Inputs:      []string{"pinX", "pinY", "kind", "net", "direction optional", "offset optional", "rotation optional"},
			Outputs:     []string{"wire primitiveId", "flag primitiveId", "end point", "rotation"},
			VerifyWith:  []string{"schematic.snapshot", "schematic.drc.check"},
		},
		{
			Name:        "schematic.select",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Select schematic primitives by id and return the active selection.",
			Inputs:      []string{"primitiveIds"},
			Outputs:     []string{"selected primitive ids"},
		},
		{
			Name:        "schematic.snapshot",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Capture current rendered area image as an artifact. Zooms to fit all primitives (适应全部) BY DEFAULT before capturing so the whole sheet lands in frame (and the viewport change nudges a redraw); pass fit=false to keep the current viewport. WARNING: EasyEDA may not auto-redraw after API edits, so the image can be a STALE frame — judge state by data (sch list/getAll), not the screenshot. Returns primitiveCount + capturedAt; if primitiveCount changed between two snapshots but the image is unchanged, the frame is stale.",
			Inputs:      []string{"fit optional (default true)"},
			Outputs:     []string{"artifact id", "file path", "mime type", "primitiveCount", "fitted", "capturedAt"},
		},
		{
			Name:        "schematic.drc.check",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Run schematic DRC and normalize the result into per-violation detail. Each violation carries {level, rule, message, primitiveIds, designators, x, y} (best-effort projection over the SDK shape, raw kept) plus a severity `summary` and a `fatal` count (error+fatal severities) for the design-flow S5 gate. `includeVerboseError` (default true) selects the detailed/array SDK overload. NOTE: the EDA schematic DRC API only returns an aggregate {count,type} (no per-item detail) — for the itemized findings the UI panel shows (which pins float, etc.), use schematic.check.",
			Inputs:      []string{"strict", "includeVerboseError"},
			Outputs:     []string{"passed", "fatal", "summary", "violations"},
		},
		{
			Name:        "schematic.check",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "Reconstructed per-item design check that the SDK's schematic DRC API cannot expose (eda.sch_Drc.check returns only an aggregate {count,type}) and that complements layout-lint (which only sees component bbox overlap). Computes findings geometrically from primitives. Rules: (1) floating pins — a pin is connected iff a wire touches its coordinate, NC-marked excluded, grouped by component as {designator, pins[]} (the exact input schematic.pin.set_no_connect takes); (2) wire-crossing — two wire segments cross in their interiors (routing tangle; shared endpoints/junctions excluded), reported with the intersection point; (3) wire-over-pin — a pin sits in a wire's interior (EasyEDA trims+connects there → unintended short). Returns {passed, summary{floatingPins,wireCrossings,wireOverPins,…}, findings[]}.",
			Inputs:      []string{"allPages optional"},
			Outputs:     []string{"passed", "summary", "findings"},
		},
		{
			Name:        "schematic.read",
			Domain:      DomainSchematic,
			Phase:       1,
			NeedsWindow: true,
			Description: "ONE-call semantic snapshot of the whole circuit — so the agent reads everything at once instead of stitching components.list + netlist + check. Returns: components[] (designator, type, name/value, footprint, supplierId=LCSC, x/y, pins[] each with its JSON-authoritative net), nets[] (net → connected {designator.pin} keys, degree, isGlobal power/ground flag), floatingPins[] (unconnected pins), and the geometric design check (same as schematic.check; pass includeCheck=false to skip for a faster read). Pin→net comes from the authoritative netlist (getNetlistFile), same source as schematic.check.",
			Inputs:      []string{"allPages optional", "includeCheck optional (default true)"},
			Outputs:     []string{"components[]", "componentCount", "nets[]", "netCount", "floatingPins[]", "floatingPinCount", "check"},
		},
		{
			Name:        "schematic.save",
			Domain:      DomainSchematic,
			Phase:       1,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Save active schematic document.",
			Outputs:     []string{"saved"},
		},
		{
			Name:        "schematic.export.netlist",
			Domain:      DomainArtifact,
			Phase:       1,
			NeedsWindow: true,
			Description: "Export schematic netlist as an artifact.",
			Inputs:      []string{"netlistType optional"},
			Outputs:     []string{"artifact id", "file path", "netlist type"},
		},
		{
			Name:        "schematic.export.bom",
			Domain:      DomainArtifact,
			Phase:       1,
			NeedsWindow: true,
			Description: "Export schematic BOM as csv or xlsx artifact.",
			Inputs:      []string{"fileType", "template optional", "columns optional"},
			Outputs:     []string{"artifact id", "file path", "file type"},
		},
		// ─── PCB (Phase 2 — read-only skeleton) ──────────────────────────
		// Connectivity probe + inspection surface for the upcoming PCB
		// layout/routing feature. All read-only; mirrors the schematic read
		// actions against the eda.pcb_* namespaces. See docs/phase-2-pcb.md.
		{
			Name:        "pcb.documents.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all PCB documents in the current project. Returns uuid + name for each board; pass uuid to document.open to switch to that PCB.",
			Outputs:     []string{"pcbs[].uuid", "pcbs[].name", "pcbs[].parentProjectUuid", "count"},
		},
		{
			Name:        "pcb.components.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List placed footprints/components on the active PCB, with layer, coordinates, rotation, lock, optional bbox (rendered extent, for overlap/spacing reasoning), and optional pads.",
			Inputs:      []string{"layer optional", "includeBBox optional", "includePads optional"},
			Outputs:     []string{"components[].primitiveId", "components[].designator", "components[].layer", "components[].x", "components[].y", "components[].rotation", "components[].bbox", "components[].pads", "count"},
		},
		{
			Name:        "pcb.layers.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all layers of the active PCB (id, name, type, color, visibility, lock), plus the current layer and copper-layer count. Activates the PCB tab first so `currentLayer` reads back reliably (#40); when there's no current layer it also returns `visibleLayers` as display-state evidence.",
			Outputs:     []string{"layers", "currentLayer", "visibleLayers", "copperLayerCount", "count"},
		},
		{
			Name:        "pcb.layers.set_current",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Switch the active/edit layer of the PCB (eda.pcb_Layer.selectLayer). Accepts `layer` as a numeric id, a layer name (e.g. Inner1), or an alias top|bottom (top copper=1, bottom copper=2). Returns the resolved layer id + the read-back currentLayer. Use before drawing/editing on a specific layer, or with pcb.snapshot for side-specific QA.",
			Inputs:      []string{"layer (id|name|top|bottom|inner1)"},
			Outputs:     []string{"ok", "requested", "layer", "currentLayer"},
			VerifyWith:  []string{"pcb.layers.list"},
		},
		{
			Name:        "pcb.layers.visibility",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Show/hide/focus PCB layers for visual QA (eda.pcb_Layer.setLayerVisible/setLayerInvisible). Either pass a `preset` (top-only|bottom-only|copper-only|silk-only) to focus that set and hide the rest, or explicit `show`/`hide` arrays of layer specs (id|name|top|bottom). With `show` + `exclusive:true`, everything else is hidden. Pair with pcb.snapshot to capture a filtered view.",
			Inputs:      []string{"preset optional (top-only|bottom-only|copper-only|silk-only)", "show optional ([]layer specs)", "hide optional ([]layer specs)", "exclusive optional (bool, hide others when showing)"},
			Outputs:     []string{"preset", "shown", "hidden", "layers"},
			VerifyWith:  []string{"pcb.layers.list", "pcb.snapshot"},
		},
		{
			Name:        "pcb.view.side",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Switch the PCB view to the top or bottom side for snapshots / human QA. Selects that side's copper as the current layer AND focuses the side's copper+silk layers so a following pcb.snapshot reflects that side (#40). NOTE: EasyEDA Pro has no native canvas flip/mirror-view API — this is a layer-focus approximation, not a physical board flip. For bottom silkscreen/copper visual QA, follow with pcb.snapshot (thread previousSha256 to defeat a stale frame).",
			Inputs:      []string{"side (top|bottom)"},
			Outputs:     []string{"side", "currentLayer", "focusedLayers", "note"},
			VerifyWith:  []string{"pcb.layers.list", "pcb.snapshot"},
		},
		{
			Name:        "pcb.stackup.set",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Configure the board stackup: set the copper layer count (`count` = 2|4|6|…|32, eda.pcb_Layer.setTheNumberOfCopperLayers) and/or set inner layers' type via `layers` ([{id, type: signal|plane, name?}] → modifyLayer; only INNER layers accept a type change). A PLANE (内电层) inner layer is the clean way to distribute GND + power on 4+ layer boards — each net gets a dedicated plane instead of two power nets fighting over one layer (the ceshi 2-layer pour-conflict that stranded 5 pads). Returns the new copperLayerCount + all layers. NOTE: changing layer count restructures the stackup — set it BEFORE routing/pouring inner layers.",
			Inputs:      []string{"count optional (2|4|6|…)", "layers optional ([{id, type: signal|plane, name?}])"},
			Outputs:     []string{"copperLayerCount", "setCount", "modified", "layers"},
			VerifyWith:  []string{"pcb.layers.list"},
		},
		{
			Name:        "pcb.silk.align",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "POSITION-AWARE auto-placement of every component's DESIGNATOR (位号). For each part it ranks the 4 sides (up/down/left/right) by LOCAL FREE SPACE (corridor clearance to the nearest obstacle) + BOARD POSITION (edge parts get pulled inward, never off-board) + a crowd-axis bonus (labels pushed PERPENDICULAR to a tight neighbor stack — the ceshi C2/C1/R1/C3 fix), then places via a ladder (base offset → grow rings → diagonals) picking the lowest-cost slot. Obstacle set (the core fix): OTHER parts' PADS (a label over exposed copper is fab-clipped — this is why C1's label no longer lands on C2's pad), component bodies, keep-out regions (mechanical=hard, copper=soft), the board outline (containment — never off-board), and other/frozen silk labels. Most-constrained-first order so tight clusters claim gaps first. Rotation stays 0 (upright, keeps `pcb check` clean); BOTTOM parts → bottom silk + mirror (with a retry-without-mirror fallback). If a part is truly boxed-in (only a pad-collision / off-board slot exists) it is LEFT in place and REPORTED in unresolved rather than moved to a worse spot. `side` biases the default; `offset` = base gap; `refs` limits to specific parts (others are frozen obstacles). Designator = component-bound ATTRIBUTE via pcb_PrimitiveAttribute.getAllPrimitiveId + .modify.",
			Inputs:      []string{"offset optional (base mil gap, default 15, ×spacing)", "spacing optional (coefficient, default 1.5 — scales label drift for assembly/solder room)", "side optional (top|bottom|left|right — soft bias)", "refs optional ([designators]; others frozen)"},
			Outputs:     []string{"aligned", "warned (body-overlap)", "unresolved (boxed-in/pad/off-board)", "skipped", "details", "unresolvedDetails", "skippedDetails"},
			VerifyWith:  []string{"pcb.silk.list", "pcb.snapshot"},
		},
		{
			Name:        "pcb.silk.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List every SILKSCREEN TEXT primitive on the active PCB — component designator/value ATTRIBUTES (pcb_PrimitiveAttribute) plus free STRINGS (pcb_PrimitiveString) — each with its silk layer (3=TOP_SILKSCREEN, 4=BOTTOM_SILKSCREEN), mirror flag, text, position, and (for attributes) the parent component's id + side (TOP/BOTTOM). Feeds the `pcb check` silkscreen-orientation rule: top silk must read un-mirrored, bottom silk must be mirrored, and a designator's silk side must match its component's side — a mismatch is a flipped/back-side silkscreen (放反). Read-only.",
			Outputs:     []string{"texts[].primitiveId", "texts[].kind", "texts[].text", "texts[].layer", "texts[].mirror", "texts[].componentId", "texts[].componentLayer", "texts[].x", "texts[].y", "count"},
		},
		{
			Name:        "pcb.silk.add",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a FREE silkscreen STRING (board marking / credit / note / logo text) at (x,y) with full config: layer (3=TOP_SILKSCREEN default, 4=BOTTOM_SILKSCREEN), fontSize (mil), lineWidth (stroke mil), rotation. Defaults font 40 / stroke 6 are legible + JLCPCB-safe — a small font (<~32 mil) with a thick stroke smears the glyphs together. Returns the new primitiveId + its rendered bbox (check it fits the board / clears parts). Use pcb.silk.set to reposition/restyle afterwards.",
			Inputs:      []string{"text (required)", "x (mil, required)", "y (mil, required)", "layer optional (3|4, default 3)", "fontSize optional (mil, default 40)", "lineWidth optional (mil, default 6)", "rotation optional (deg, default 0)"},
			Outputs:     []string{"primitiveId", "layer", "x", "y", "fontSize", "lineWidth", "rotation", "bbox"},
			VerifyWith:  []string{"pcb.silk.list", "pcb.snapshot"},
		},
		{
			Name:        "pcb.silk.set",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Reconfigure existing silkscreen primitive(s) in ONE batch — designator/value ATTRIBUTES and free STRINGS alike. Provide primitiveIds ([] or one) + any of x/y/rotation/fontSize/lineWidth/text; only the given keys change. ALSO an ALIGN shortcut: pass `align` (center|mid = both axes, centerx|centery, left|right|top|bottom = edge-align) + `ref` (a component designator, \"board\"/\"outline\", or \"fill\"; default board) to position each silk relative to that reference bbox — computed from the silk's OWN bbox so its center/edge lands exactly on the reference (e.g. center the board credit, or align a label to a component's top). Uses the reliable .modify(id,props) (NOTE: setState_Rotation alone does NOT persist; a snapshot taken before a document reload shows the OLD orientation — judge by pcb.silk.list/pcb check, not a stale screenshot). The batch position/orientation/size/align adjuster; pair with pcb.silk.list (get ids) and pcb check (silkscreen-flipped).",
			Inputs:      []string{"primitiveIds (string or [] , required)", "x optional (mil)", "y optional (mil)", "rotation optional (deg)", "fontSize optional (mil)", "lineWidth optional (mil)", "text optional", "align optional (center|mid|centerx|centery|left|right|top|bottom)", "ref optional (designator|board|outline|fill, default board)"},
			Outputs:     []string{"align", "count", "results[].primitiveId", "results[].ok", "results[].x", "results[].y"},
			VerifyWith:  []string{"pcb.silk.list"},
		},
		{
			Name:        "pcb.nets.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all nets on the active PCB with name, length, and color.",
			Outputs:     []string{"nets[].net", "nets[].length", "nets[].color", "count"},
		},
		{
			Name:        "pcb.report",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read-only PCB design report driven by per-net copper length: every net's routed length, each net class's aggregate length, differential-pair P/N lengths + skew (|lenP-lenN|), and equal-length-group per-net lengths + spread (max-min). Pure read — no DRC run. pcb_Drc.* reads may require the PCB to be the active/foreground tab.",
			Outputs:     []string{"nets[].net", "nets[].length", "netClasses[].name", "netClasses[].totalLength", "differentialPairs[].skew", "equalLengthNetGroups[].spread"},
		},
		// ─── PCB (Phase 2 — schematic→PCB sync + component layout) ────────
		// Components arrive on the board via pcb.import_changes (from the
		// schematic), then get laid out with pcb.component.modify. See
		// docs/phase-2-pcb.md.
		{
			Name:        "pcb.board.info",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the current Board (schematic+PCB linkage) and current PCB info — the prerequisite context for pcb.import_changes.",
			Outputs:     []string{"linked", "board", "pcb"},
		},
		// ── board (板子/组合 — the schematic↔PCB binding) ──────────────────
		// A Board groups exactly one schematic + one PCB; it is identified by
		// NAME (not uuid). All map to eda.dmt_Board.*. Domain-agnostic routing.
		{
			Name:        "board.list",
			Domain:      DomainBoard,
			Phase:       2,
			NeedsWindow: true,
			Description: "List all Boards (板子) in the current project. A Board binds one schematic + one PCB into a group — this is how schematic and PCB are kept together (and what import_changes follows).",
			Outputs:     []string{"boards (name + schematic + pcb)"},
		},
		{
			Name:        "board.current",
			Domain:      DomainBoard,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the current Board (its bound schematic + PCB).",
			Outputs:     []string{"linked", "board"},
		},
		{
			Name:        "board.create",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a Board binding a schematic and/or a PCB into one group (组合). Pass schematicUuid and/or pcbUuid; returns the new board name.",
			Inputs:      []string{"schematicUuid optional", "pcbUuid optional"},
			Outputs:     []string{"boardName"},
			VerifyWith:  []string{"board.list"},
		},
		{
			Name:        "board.new_pcb",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a NEW board (板) containing a fresh empty PCB page, bound to a schematic — the 新建PCB / 原理图转PCB flow. Unlike board.create (which only links existing docs), this mints a real new PCB you can switch to and import-changes into. Runs the required 2-step SDK sequence (createBoard shell → createPcb into it) with rollback. Defaults the schematic to the current board's if omitted.",
			Inputs:      []string{"schematicUuid optional (default = current board's schematic)", "name optional (rename the new board)"},
			Outputs:     []string{"boardName", "pcbName", "pcbUuid", "schematicUuid"},
			VerifyWith:  []string{"board.list", "pcb.docs"},
		},
		{
			Name:        "board.rename",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Rename a Board (板子) by its current name.",
			Inputs:      []string{"name", "newName"},
			Outputs:     []string{"ok"},
		},
		{
			Name:        "board.copy",
			Domain:      DomainBoard,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Copy a Board (its schematic + PCB) into a new Board; returns the new board name.",
			Inputs:      []string{"name"},
			Outputs:     []string{"boardName"},
			VerifyWith:  []string{"board.list"},
		},
		{
			Name:         "board.delete",
			Domain:       DomainBoard,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete a Board by name (无 undo). Removes the schematic↔PCB grouping and its documents.",
			Inputs:       []string{"name"},
			Outputs:      []string{"ok"},
		},
		{
			Name:         "pcb.import_changes",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Sync the schematic netlist/components into the active PCB (从原理图导入变更) — how components first arrive on the board. Ensures a Board links the schematic and PCB first, then recomputes ratlines. ⚠️ LIMITATION (verified #20): eda.pcb_Document.importChanges does NOT add components placed via the API (schematic.component.place) to an EXISTING PCB — even though the new part is in the canvas AND the manufacture netlist with a designator + footprint, importChanges returns true but the PCB count is unchanged (default or explicit schematicUuid; no annotate/refresh/updatePcb API exists to force it). It works for the initial board population; incrementally adding a part via the API then importing is a platform no-op — **to add a single part to an existing PCB use pcb.add_component instead** (places + connects it directly).",
			Inputs:       []string{"schematicUuid optional", "ensureBoard optional (default true)", "recomputeRatline optional (default true)"},
			Outputs:      []string{"imported", "createdBoard", "board", "reason"},
			VerifyWith:   []string{"pcb.components.list", "pcb.nets.list"},
		},
		{
			Name:         "pcb.add_component",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Place a footprint on the PCB and CONNECT it — the WORKING way to add ONE part to an existing board, since pcb.import_changes no-ops for API-added parts (#20). Creates the footprint (device {libraryUuid, uuid}) at x,y on a copper layer, links it to its schematic twin (uniqueId + designator), assigns each pad's net from the supplied `nets` map (padNumber→net) via pad-net writes, then recomputes ratlines. Net→pad assignment is what actually wires it (importChanges normally does that). Get `nets` (and the twin's uniqueId) from `sch read` — the netlist is only readable while the schematic is active, so the caller passes it. Workflow: place+wire the part in the schematic → `sch read` for its pin nets + uniqueId → `pcb add-component` with those nets.",
			Inputs:       []string{"libraryUuid", "uuid", "x", "y", "layer optional (default 1=TOP)", "rotation optional", "designator optional", "uniqueId optional", "nets optional (object padNumber→net)"},
			Outputs:      []string{"primitiveId", "designator", "uniqueId", "padCount", "assignedNets", "unmatchedPads"},
			VerifyWith:   []string{"pcb.components.list", "pcb.nets.list", "pcb.drc.check"},
		},
		{
			Name:        "pcb.component.modify",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Lay out a component on the active PCB: move (x/y), rotate, flip layer (top/bottom), lock, or set designator/BOM flags. Pull a fresh primitiveId first (no programmatic undo).",
			Inputs:      []string{"primitiveId", "patch"},
			Outputs:     []string{"component state"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:         "pcb.component.delete",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete PCB component primitives. No programmatic undo — snapshot before/after via the audit log.",
			Inputs:       []string{"primitiveIds"},
			Outputs:      []string{"deleted"},
			VerifyWith:   []string{"pcb.components.list"},
		},
		// ─── PCB layout-adjustment (deterministic; no native align/grid API) ──
		// Read each component's bbox + anchor, compute, write absolute x/y.
		// Operate on the current selection by default, or explicit primitiveIds.
		{
			Name:        "pcb.align",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Align components by an edge or center. mode = left|right|top|bottom|centerX|centerY (top/bottom are y-up: top = larger y). Aligns to the group extent. Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"mode", "primitiveIds optional"},
			Outputs:     []string{"moved[].primitiveId", "moved[].designator", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.distribute",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Evenly space component centers along an axis. axis = x|y. Keeps the two extreme components fixed and distributes the rest between them. Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"axis", "primitiveIds optional"},
			Outputs:     []string{"moved[].primitiveId", "moved[].designator", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.grid_snap",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Snap component anchors to a grid: round x/y to the nearest multiple of grid (in PCB data units, mil-scale). Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"grid", "primitiveIds optional"},
			Outputs:     []string{"snapped[].primitiveId", "snapped[].from", "snapped[].to", "grid", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.components.move",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Translate components by a relative (dx, dy) offset — nudge a group without recomputing absolute coordinates. Operates on the current selection unless primitiveIds is given.",
			Inputs:      []string{"dx", "dy", "primitiveIds optional"},
			Outputs:     []string{"moved[].primitiveId", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.components.arrange",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Coarse auto-layout SEED: cluster by shared local nets (mode=cluster) or pack a flat grid (mode=grid), grid-packing each cluster into a tidy block with gutters; skips locked components. Mechanical first pass only — apply the placement priorities in pcb-layout-conventions.md afterward.",
			Inputs:      []string{"mode optional (cluster|grid, default cluster)", "primitiveIds optional", "pitch optional", "gutter optional", "cols optional"},
			Outputs:     []string{"mode", "groups", "moved[].primitiveId", "moved[].from", "moved[].to", "count"},
			VerifyWith:  []string{"pcb.components.list"},
		},
		{
			Name:        "pcb.drc.check",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Run PCB DRC, normalized to {passed, violations}; violations are grouped by error type then net. Requires the PCB to be the active/foreground document.",
			Inputs:      []string{"strict optional"},
			Outputs:     []string{"passed", "violations"},
		},
		{
			Name:        "pcb.drc.rules",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the active PCB's DRC rule configuration (clearances, track widths, via sizes, …) WITHOUT running a check — inspect what pcb.drc.check enforces, or feed real rule values into layout-lint / design-flow gates. Requires the PCB to be the active/foreground document.",
			Outputs:     []string{"rules"},
		},
		// ─── PCB routing (copper tracks + vias) ──────────────────────────
		// Real routing primitives — additive creates (no confirm), like the
		// schematic wire/netflag creates. Bind to a net by NAME; pull layer ids
		// from pcb.layers.list and net names from pcb.nets.list first.
		{
			Name:        "pcb.line.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a copper track (导线) on the active PCB: a line segment on a copper layer (TOP=1, BOTTOM=2; inner-copper ids are higher — read them from pcb.layers.list, id 3 is silkscreen not copper) with a width, optionally bound to a net. Coordinates are mil, y-up. create() is lenient — the action verifies a primitive came back. PCB autosave is on (debounced); save explicitly at checkpoints.",
			Inputs:      []string{"startX", "startY", "endX", "endY", "layer optional (default 1=TOP)", "lineWidth optional (default 6)", "net optional"},
			Outputs:     []string{"primitiveId", "net", "layer", "start", "end", "lineWidth"},
			VerifyWith:  []string{"pcb.drc.check"},
		},
		{
			Name:        "pcb.via.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Place a via (过孔) at (x,y) on the active PCB with a hole + outer diameter (mil), optionally bound to a net. Coordinates are mil, y-up. create() is lenient — the action verifies a primitive came back. PCB autosave is on (debounced); save explicitly at checkpoints.",
			Inputs:      []string{"x", "y", "holeDiameter optional", "diameter optional", "net optional"},
			Outputs:     []string{"primitiveId", "net", "x", "y", "holeDiameter", "diameter"},
			VerifyWith:  []string{"pcb.drc.check"},
		},
		{
			Name:        "pcb.save",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Save the active PCB document to disk (eda.pcb_Document.save). The PCB counterpart to schematic.save — PCB edits are in-memory until saved. Also the action the daemon's debounced autosave fires for a PCB window.",
			Outputs:     []string{"saved"},
		},
		// ─── Freerouting round-trip (export DSN → external router → import SES) ──
		{
			Name:        "pcb.export.dsn",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Export the active PCB as a Specctra DSN file (eda.pcb_ManufactureData.getDsnFile) — the input an external autorouter (Freerouting / easyeda-pcb-router) consumes. Read-only. Returns null if the PCB is empty or has no nets (run pcb.import_changes first). By DEFAULT it injects keep-out regions (禁止区域) into the DSN — getDsnFile DROPS pcb_PrimitiveRegion, so a raw export has 0 keepout and the router would route under the antenna; the injected DSN reports keepouts=N. Pass injectKeepout=false for the raw export. The autoroute round-trip: export.dsn → route externally → import_autoroute the SES.",
			Inputs:      []string{"fileName optional", "injectKeepout optional (default true)"},
			Outputs:     []string{"artifact id", "file path", "file name", "size", "keepouts (injected count)"},
		},
		{
			Name:        "pcb.import_autoroute",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Import a routed-result file from an external autorouter into the active PCB: format='ses' (Specctra Session, default; eda.pcb_Document.importAutoRouteSesFile) or 'json' (eda.pcb_Document.importAutoRouteJsonFile). File passed as base64 (fileBase64). The write side of the DSN→route→SES round-trip; recomputes ratlines after. Both APIs are @beta.",
			Inputs:      []string{"fileBase64", "format optional (ses|json, default ses)", "fileName optional"},
			Outputs:     []string{"imported", "format"},
		},
		{
			Name:        "pcb.snapshot",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Capture the active PCB canvas as a PNG artifact (eda.dmt_EditorControl.getCurrentRenderedAreaImage; fit-to-all by default, pass fit=false to keep viewport). The PCB counterpart to schematic.snapshot. Returns a frame sha256 — pass it back via previousSha256 on the next snapshot and the connector detects a byte-identical (stale) frame, forces a redraw (ratline recompute + zoom-to-all) + retries once, and reports stale=true if it is still identical. WARNING: EasyEDA may return a STALE frame after API edits — judge layout/DRC by data (pcb list / pcb drc), screenshot for a human eyeball only.",
			Inputs:      []string{"fit optional (default true)", "tabId optional", "previousSha256 optional (enables stale-frame detection + auto-retry)"},
			Outputs:     []string{"artifact id", "file path", "fitted", "sha256", "stale", "staleRetry", "capturedAt"},
		},
		// ─── PCB routing: list + rip-up (iterate/clear copper routing) ────
		{
			Name:        "pcb.line.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List copper tracks (导线) on the active PCB, optionally filtered by net and/or layer. Read-only — use to inspect what is routed before rip-up/reroute.",
			Inputs:      []string{"net optional", "layer optional"},
			Outputs:     []string{"lines[].primitiveId", "lines[].net", "lines[].layer", "lines[].startX", "lines[].startY", "lines[].endX", "lines[].endY", "lines[].lineWidth", "lines[].locked", "count"},
		},
		{
			Name:        "pcb.via.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List vias (过孔) on the active PCB, optionally filtered by net. Read-only.",
			Inputs:      []string{"net optional"},
			Outputs:     []string{"vias[].primitiveId", "vias[].net", "vias[].x", "vias[].y", "vias[].holeDiameter", "vias[].diameter", "vias[].locked", "count"},
		},
		{
			Name:         "pcb.route.rip_up",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Rip up copper routing (delete tracks + arcs + vias) — reliable hand-rolled rip-up (getAll → filter → delete) on the stable primitive APIs. Pass net (string or string[]) to rip up only those nets; omit to rip up ALL routing. Deletes COPPER layers ONLY (TOP/BOTTOM/INNER) — never silkscreen/assembly/mechanical artwork, the board outline, or locked primitives. The iteration primitive: rip_up → re-route. delete() is a batch boolean, so results report requested counts + ok, not an assumed deleted count.",
			Inputs:       []string{"net optional (string or string[]); omit = all"},
			Outputs:      []string{"nets", "lines{requested,ok}", "arcs{requested,ok}", "vias{requested,ok}"},
			VerifyWith:   []string{"pcb.line.list", "pcb.via.list"},
		},
		{
			Name:         "pcb.route.delete",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Surgically delete routing primitives (tracks/arcs/vias) by primitiveId — the precise fix rip_up can't do (rip_up is net-scoped: one bad via would force re-routing the whole net). Ids are classified against the live board; locked primitives are skipped, unknown ids reported as notFound (pull fresh ids from pcb.line.list / pcb.via.list / pcb drc --json objs). Optional kind ('via'|'track') refuses mismatched ids as a paste-guard. Each removed primitive's FULL before-state (net/layer/geometry) is echoed in `removed` so the audit log can recreate it.",
			Inputs:       []string{"primitiveIds (string or string[])", "kind optional (via|track — refuse ids of another kind)"},
			Outputs:      []string{"deleted{tracks,arcs,vias}{requested,ok}", "removed[] (full before-state)", "count", "skippedLocked", "notFound"},
			VerifyWith:   []string{"pcb.line.list", "pcb.via.list", "pcb.drc.check"},
		},
		{
			Name:        "pcb.route.via_hop",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Composite layer hop for one net: entry stub → via → hop-layer track → via → exit stub, PLUS (default on) a small net-bound bond FILL on both layers of both vias. The fills are load-bearing: on 4-layer / ex-PLANE boards a track touching a via does NOT register as connected (pro-api-sdk#31) — an overlapping net-bound fill is the only reliable bridge. Vias sit `stub` mil inside the endpoints (keeps them OFF pads — via-on-pad ≠ connected). Rolls back all created primitives on mid-sequence failure. Verify with pcb.drc.check.",
			Inputs:      []string{"net", "fromX", "fromY", "toX", "toY", "layer optional (default 1=TOP)", "hopLayer optional (default 2=BOTTOM)", "lineWidth optional (default 6)", "holeDiameter optional (default 12)", "viaDiameter optional (default 24)", "stub optional (default 20 mil)", "bondFill optional (default true)", "bondSize optional (default 20 mil)"},
			Outputs:     []string{"net", "layer", "hopLayer", "vias[]{x,y}", "trackIds", "viaIds", "fillIds", "bonded", "note"},
			VerifyWith:  []string{"pcb.drc.check", "pcb.via.list"},
		},
		{
			Name:         "pcb.clear_routing",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Clear routing via the native eda.pcb_Document.clearRouting('all'|'net'|'connection'). NOTE: @alpha — may be undefined on the current build (like autoRouting); prefer pcb.route.rip_up for a reliable, outline-safe rip-up. Unlike rip_up this does NOT protect unlocked board-outline lines, so lock the outline first.",
			Inputs:       []string{"type optional (all|net|connection, default all)"},
			Outputs:      []string{"cleared", "type"},
		},
		// ─── PCB copper pour (铺铜) ───────────────────────────────────────
		// Build polygon (pcb_MathPolygon.createPolygon) → pour.create → rebuild.
		{
			Name:        "pcb.pour.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a copper pour (铺铜) from a closed polygon of points (mil, y-up) on a copper layer (TOP=1, BOTTOM=2; inner ids from pcb.layers.list), bound to a net (usually GND). fill = solid (default) | grid | grid45. Builds the IPCB_Polygon internally (pcb_MathPolygon.createPolygon) — pass raw points, NOT a polygon object — then rebuilds the poured copper. No PCB autorouter, but this gives real ground/power planes.",
			Inputs:      []string{"points ([[x,y],...] mil)", "net optional (default '')", "layer optional (default 1=TOP)", "fill optional (solid|grid|grid45)", "name optional", "priority optional", "lineWidth optional"},
			Outputs:     []string{"primitiveId", "net", "layer", "fill", "poured"},
			VerifyWith:  []string{"pcb.pour.list", "pcb.drc.check"},
		},
		{
			Name:        "pcb.pour.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List copper pours (铺铜) on the active PCB, optionally filtered by net. Read-only.",
			Inputs:      []string{"net optional"},
			Outputs:     []string{"pours[].primitiveId", "pours[].net", "pours[].layer", "pours[].pourName", "pours[].priority", "pours[].lineWidth", "pours[].locked", "count"},
		},
		{
			Name:         "pcb.pour.delete",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete copper pour regions by primitiveId (string or string[]). Removes the pour region; recreate with pcb.pour.create.",
			Inputs:       []string{"primitiveIds (string or string[])"},
			Outputs:      []string{"deleted", "primitiveIds"},
			VerifyWith:   []string{"pcb.pour.list"},
		},
		{
			Name:        "pcb.pour.rebuild",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Re-pour (recompute poured copper) for all pour regions on the active PCB, optionally filtered by net. Run after moving components/routing so the pour reflows around the new obstacles (rebuildCopperRegion per pour).",
			Inputs:      []string{"net optional"},
			Outputs:     []string{"pours", "rebuilt"},
		},
		// ─── PCB region (禁止区域 / 规则区域 keep-out) ──────────────────────
		// pcb_PrimitiveRegion: a polygon carrying RULE types (keep components/
		// wires/copper out) — antenna clearance, board-edge inset, mechanical
		// exclusion. NOT net-bound filled copper (that's pcb.pour.create).
		{
			Name:        "pcb.region.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a keep-out / rule region (禁止区域) from a closed polygon of points (mil, y-up) on a copper layer (TOP=1, BOTTOM=2; or MULTI for all). ruleType is a name or list — no-components(2) / no-wires(5) / no-fills(6) / no-pours(7) / no-inner-electrical(8) / follow-rule(9); default [no-components,no-wires,no-pours] = a hard keep-out (antenna/board-edge). Builds the IPCB_Polygon internally — pass raw points, NOT a polygon object. This is NOT net-bound copper (use pcb.pour.create for a ground/power plane). NOTE: `name` is fire-and-forget — EasyEDA's getState_RegionName never reads it back (platform limit, verified), so region.list shows null and the DSN keepout name falls back to region_keepout_N; geometry/layer/ruleType DO persist and read back.",
			Inputs:      []string{"points ([[x,y],...] mil)", "layer optional (default 1=TOP)", "ruleType optional (name|number or list; default keep-out)", "name optional", "lineWidth optional", "locked optional"},
			Outputs:     []string{"primitiveId", "layer", "ruleType", "ruleTypeNames", "regionName"},
			VerifyWith:  []string{"pcb.region.list", "pcb.drc.check"},
		},
		{
			Name:        "pcb.region.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List keep-out / rule regions (禁止区域) on the active PCB, optionally filtered by layer. Read-only.",
			Inputs:      []string{"layer optional"},
			Outputs:     []string{"regions[].primitiveId", "regions[].layer", "regions[].ruleType", "regions[].ruleTypeNames", "regions[].regionName", "regions[].lineWidth", "regions[].locked", "count"},
		},
		{
			Name:         "pcb.region.delete",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete keep-out / rule regions by primitiveId (string or string[]). Note pcb.delete (component delete) does NOT remove regions — use this. Recreate with pcb.region.create.",
			Inputs:       []string{"primitiveIds (string or string[])"},
			Outputs:      []string{"deleted", "primitiveIds"},
			VerifyWith:   []string{"pcb.region.list"},
		},
		// ─── PCB fill (填充区域 / net-bound solid copper) ──────────────────
		// pcb_PrimitiveFill: a net-bound STATIC filled polygon (3V3/RF-ground
		// patch, thermal copper, odd plane). DISTINCT from keep-out region (no
		// net) AND from pour (覆铜, which reflows). Does NOT reflow around obstacles.
		{
			Name:        "pcb.fill.create",
			Domain:      DomainPcb,
			Phase:       2,
			Mutates:     true,
			NeedsWindow: true,
			Description: "Create a net-bound filled region (填充区域 / 异形大块铜) from a closed polygon of points (mil, y-up) on a layer (TOP=1, BOTTOM=2), bound to a net. fillMode = solid (default) | mesh | inner. Builds the IPCB_Polygon internally — pass raw points. This is STATIC copper (does NOT reflow) — distinct from pcb.pour.create (覆铜, reflows around obstacles) and pcb.region.create (keep-out, no net). Use for a power-plane patch / RF ground / thermal copper of an arbitrary shape. SPECIAL CASE: layer=MULTI(12) makes the fill a 挖槽/board CUTOUT (removes board material; the manufacturing output emits it as a BoardCutout object) — no net needed; the `pcb slot` CLI wraps this. NOTE: fillMode is fire-and-forget — EasyEDA's getState_FillMode always reads back solid(0) regardless of input (platform limit, verified via modify too), so prefer solid; net/layer/geometry persist and read back correctly.",
			Inputs:      []string{"points ([[x,y],...] mil)", "net optional", "layer optional (default 1=TOP)", "fillMode optional (solid|mesh|inner)", "lineWidth optional", "locked optional"},
			Outputs:     []string{"primitiveId", "net", "layer", "fillMode"},
			VerifyWith:  []string{"pcb.fill.list", "pcb.drc.check"},
		},
		{
			Name:        "pcb.fill.list",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "List net-bound filled regions (填充区域) on the active PCB, optionally filtered by layer and/or net. includeBBox adds each fill's rendered extent (per-fill getPrimitivesBBox; null on failure) — feeds the `pcb check` via-bond rule (is this track↔via junction covered by a bond fill?). Read-only.",
			Inputs:      []string{"layer optional", "net optional", "includeBBox optional (default false)"},
			Outputs:     []string{"fills[].primitiveId", "fills[].net", "fills[].layer", "fills[].fillMode", "fills[].lineWidth", "fills[].locked", "fills[].bbox (includeBBox)", "count"},
		},
		{
			Name:         "pcb.fill.delete",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Delete net-bound filled regions (填充区域) by primitiveId (string or string[]). Recreate with pcb.fill.create.",
			Inputs:       []string{"primitiveIds (string or string[])"},
			Outputs:      []string{"deleted", "primitiveIds"},
			VerifyWith:   []string{"pcb.fill.list"},
		},
		// ─── Board outline (板框) — closed polyline on the BOARD_OUTLINE layer ──
		// Curves are line-segment approximated (native arcs do not commit on the
		// current build). Shape-generation recipes (rect/rounded-rect/circle/
		// instrument) live in the easyeda-agent skill; these actions just render points.
		{
			Name:         "pcb.outline.set",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Set the board outline from a closed polygon of points (mil, y-up). Creates ONE pcb_PrimitivePolyline (类型=板框) on the Board Outline Layer (11) — the REAL board-outline object, not loose lines. Loose pcb_PrimitiveLine on layer 11 are merely wires sitting there: EasyEDA does NOT treat them as the boundary — DRC ignores them for enclosure and the UI '清除布线 / clear routing' deletes them (observed: the whole outline vanished). The polyline is created LOCKED so layout/routing can't move or wipe it. Replaces any existing outline (polyline + legacy lines/arcs). The agent generates the points for the desired shape (rectangle/rounded-rect/circle/instrument); curves are approximated by segments. Reports outlineId + whether all components fall inside.",
			Inputs:       []string{"points ([[x,y],...] mil)", "replace optional (default true)", "lineWidth optional (default 10)"},
			Outputs:      []string{"outlineId", "segments", "zoomed", "bbox", "allInside", "outside"},
			VerifyWith:   []string{"pcb.outline.get"},
		},
		{
			Name:        "pcb.outline.get",
			Domain:      DomainPcb,
			Phase:       2,
			NeedsWindow: true,
			Description: "Read the current board outline: outline (polyline 类型=板框 count) + legacy segment/arc counts + bounding box (from the polyline's rendered extent).",
			Outputs:     []string{"outline", "segments", "arcs", "bbox"},
		},
		{
			Name:         "pcb.outline.clear",
			Domain:       DomainPcb,
			Phase:        2,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Remove the current board outline (all primitives on the BOARD_OUTLINE layer).",
			Outputs:      []string{"removed"},
			VerifyWith:   []string{"pcb.outline.get"},
		},
		{
			Name:         "debug.exec_js",
			Domain:       DomainDebug,
			Phase:        1,
			Mutates:      true,
			NeedsWindow:  true,
			NeedsConfirm: true,
			Description:  "Run raw eda.* JavaScript in the connector. Escape hatch for operations without a typed action; confirmation-gated, not for normal workflows.",
			Inputs:       []string{"code"},
			Outputs:      []string{"value"},
		},
	}
}
